### ISSUE TITLE
Example for create address, send coins

### ISSUE THREAD

**Issue by kunalransing** [strategyobject/substrate-client-java#17]
Hi,
I'm new to polkadot. I'm working on project which will create address, receive coins & send coins etc. I have checked project but didn't find any sample example for such. 
Please help me for this.
Thanks.

**Comment by kalaninja** [comment]
HI @kunalransing we've added a [sample project](https://github.com/strategyobject/substrate-client-sample) now that shows how to use the latest release of the client.

**Comment by kalaninja** [comment]
I'll close this issue. Please, feel free to reopen it, if needed.
