### ISSUE TITLE
Question: Extrinsic Support

### ISSUE THREAD

**Issue by pfrank13** [strategyobject/substrate-client-java#42]
As I understand it there is no declarative support, via annotation, for Extrinisics but is there a way to piece together that support with what currently does exist? I'm not super versed on how Extrinsics work at a spec level so I'm not entirely sure, some of the examples in the wiki make me think there may be support but I'm not recognizing it because of my ignorance, If there is a way to piece together that support can you provide an example or point me to one?

Thanks!

**Comment by pfrank13** [comment]
I believe the answer is yes, with examples being here https://github.com/strategyobject/substrate-client-java/blob/develop/api/src/test/java/com/strategyobject/substrateclient/api/pallet/balances/BalancesTest.java#L51 and https://github.com/strategyobject/substrate-client-java/blob/develop/rpc/rpc-api/src/test/java/com/strategyobject/substrateclient/rpc/api/section/AuthorTests.java#L80-L93

**Comment by kalaninja** [comment]
@pfrank13 there is no declarative approach for extrinsics right now. You'll have to implement it manually. An example can be found [here](https://github.com/strategyobject/substrate-client-examples/blob/7ea7ec063bc167a42c6508556c958005bb8277a1/balance-transfer/src/main/java/com/strategyobject/substrateclient/examples/balancetransfer/BalancePalletImpl.java#L51)

**Comment by pfrank13** [comment]
Awesome, I'll take a look at that. Thank you very much!
